version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
configuration: Release
before_build:
   - nuget restore src
build:
  project: src/Nager.ConfigParser.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal